export const GlobalConst = {
  zcash: 'wcash:',
  port80: '80',
  port443: '443',
  port9067: '9067',
  http: 'http:',
  https: 'https:',
  serverPlaceHolder: 'https://------.---:---',
  uview: 'uview',
  uviewtest: 'uviewtest',
  uviewregtest: 'uviewregtest',
  success: 'success',
  true: 'true',
  false: 'false',
  memoMaxLength: 511,
  platformOSios: 'ios',
  platformOSandroid: 'android',
  blocksPerBatch: 100,
  yes: 'yes',
  no: 'no',
  background: '@background',
  keyKeyChain: 'WCASH_WALLET_SEED_BIRTHDAY',
  serviceKeyChain: 'WCASH_WALLET',
  replyTo: '\nReply to: \n',
  expireBlocks: 40,
  zingolib: 'Zingolib',
  zingolibError: '<error>',
  zingolibNone: '<none>',
  transactionFilterThreshold: '500',
  keyChain: 'KeyChain',
  keyStore: 'KeyStore',
  utf8: 'utf8',
  minConfirmations: 3,
  // Internal upstream chain code. The visible ticker is WEC; retaining this
  // key avoids changing the address-book and swap component structure.
  // It branches native-Wcash vs external-chain validation paths.
  zecSwapChain: 'ZEC',
};
