name: Create cache key

on:
  workflow_call:
    outputs:
      cache-key:
        description: "Cache key"
        value: ${{ jobs.create-cache-key.outputs.cache-key }}

jobs:
  create-cache-key:
    name: Create cache key
    runs-on: ubuntu-24.04
    outputs:
      cache-key: ${{ steps.create-cache-key.outputs.cache-key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Store Cargo version
        run: echo $(cargo --version) >> rust/cargo_version.txt

      - name: Create cache key
        id: create-cache-key
        run: echo "cache-key=${{ hashFiles('rust/**/Cargo.toml', 'rust/**/Cargo.lock', 'rust/**/uniffi.toml', 'rust/**/*.rs', 'rust/cargo_version.txt') }}" >> $GITHUB_OUTPUT
